const PRODUCTS = [
  {
    id: 1,
    name: "Naatusakkarai",
    image: "/products/Naatusakkarai.png",
    price: 150,
    rating: 4.8,
    unit: "500g",
    category: "Natural Sweeteners",
    isBestSeller: true,
  },
  {
    id: 2,
    name: "Amla Candy",
    image: "/products/amla candy.png",
    price: 120,
    rating: 4.5,
    unit: "250g",
    category: "Traditional Snacks",
  },
  {
    id: 3,
    name: "Himalayan Rock Salt Crystal",
    image: "/products/himalayan rock salt crystal.png",
    price: 180,
    rating: 4.6,
    unit: "500g",
    category: "Himalayan Salts",
    isBestSeller: true,
  },
  {
    id: 4,
    name: "Himalayan Rock Salt Crystal (Large)",
    image: "/products/himalayan rock salt crystal - 2.png",
    price: 350,
    rating: 4.7,
    unit: "1kg",
    category: "Himalayan Salts",
  },
  {
    id: 5,
    name: "Himalayan Rock Salt Pink",
    image: "/products/himalayan rocksalt pink.png",
    price: 190,
    rating: 4.8,
    unit: "500g",
    category: "Himalayan Salts",
  },
  {
    id: 6,
    name: "Himalayan Rock Salt Pink (Large)",
    image: "/products/himalayan rocksalt pink - 2.png",
    price: 360,
    rating: 4.7,
    unit: "1kg",
    category: "Himalayan Salts",
  },
  {
    id: 7,
    name: "Honey with Dry Fig",
    image: "/products/hone with dry fig.png",
    price: 450,
    rating: 4.9,
    unit: "500g",
    category: "Honey & Bee Products",
    isBestSeller: true,
  },
  {
    id: 8,
    name: "Honey with Dry Fruits",
    image: "/products/hone with dry fruits.png",
    price: 500,
    rating: 4.8,
    unit: "500g",
    category: "Honey & Bee Products",
  },
  {
    id: 9,
    name: "Honey Amla",
    image: "/products/honey amla.png",
    price: 320,
    rating: 4.7,
    unit: "500g",
    category: "Honey & Bee Products",
  },
  {
    id: 10,
    name: "Honey Amla (Large)",
    image: "/products/honey amla - 2.png",
    price: 600,
    rating: 4.6,
    unit: "1kg",
    category: "Honey & Bee Products",
  },
  {
    id: 11,
    name: "Kadalai Mittai (Peanut Chikki)",
    image: "/products/kadalai mittai (Peanut Chikki).png",
    price: 90,
    rating: 4.9,
    unit: "250g",
    category: "Traditional Snacks",
    isBestSeller: true,
  },
  {
    id: 12,
    name: "Kombu Then",
    image: "/products/kombu then.png",
    price: 550,
    rating: 4.8,
    unit: "500g",
    category: "Honey & Bee Products",
  },
  {
    id: 13,
    name: "Malai Then (Hill Honey)",
    image: "/products/malai then (Hill Honey).png",
    price: 600,
    rating: 4.9,
    unit: "500g",
    category: "Honey & Bee Products",
  },
  {
    id: 14,
    name: "Millet Cookie",
    image: "/products/millet cookie.png",
    price: 150,
    rating: 4.7,
    unit: "200g",
    category: "Healthy Cookies",
    isBestSeller: true,
  },
  {
    id: 15,
    name: "Millet Cookie (Large)",
    image: "/products/millet cookie - 2.png",
    price: 280,
    rating: 4.8,
    unit: "400g",
    category: "Healthy Cookies",
  },
  {
    id: 16,
    name: "Palm Candy",
    image: "/products/palm candy.png",
    price: 250,
    rating: 4.7,
    unit: "250g",
    category: "Natural Sweeteners",
    isBestSeller: true,
  },
  {
    id: 17,
    name: "Panamkarkandu",
    image: "/products/panamkarkandu.png",
    price: 260,
    rating: 4.9,
    unit: "500g",
    category: "Natural Sweeteners",
  },
  {
    id: 18,
    name: "Panamkarkandu (250g)",
    image: "/products/panamkarkandu 250.png",
    price: 140,
    rating: 4.8,
    unit: "250g",
    category: "Natural Sweeteners",
  }
];

let CATEGORIES = []

PRODUCTS.forEach(p => {
  if (!CATEGORIES.includes(p.category)) {
    CATEGORIES.push(p.category)
  }
})

export { PRODUCTS, CATEGORIES };
